version: '3.3'

services:

  mysql:
    image: mysql:5.7.21
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:      school
      MYSQL_USER:          school
      MYSQL_PASSWORD:      school
    volumes:
     - mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
     - "8008:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

volumes:
  mysqldata:
    driver: "local"